import React from 'react';

interface HelpModalProps {
  onClose: () => void;
}

const HelpSection: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="mb-5">
    <h3 className="text-xl font-bold text-cyan-300 mb-2 uppercase tracking-wider">{title}</h3>
    <div className="text-gray-300 space-y-2 text-left">{children}</div>
  </div>
);

const HelpModal: React.FC<HelpModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4" onClick={onClose}>
      <div 
        className="bg-[#0A0F1E] border-2 border-cyan-500 rounded-lg shadow-2xl p-6 sm:p-8 max-w-2xl w-full text-center clip-corner glow-cyan-lg max-h-[90vh] flex flex-col"
        onClick={e => e.stopPropagation()} // Prevent closing when clicking inside
      >
        <h2 className="text-3xl font-bold text-cyan-300 mb-4 uppercase tracking-wider flex-shrink-0">How to Play</h2>
        
        <div className="overflow-y-auto pr-4 space-y-4">
            <HelpSection title="🚀 The Goal">
                <p>Your ultimate objective is to become a master of stellar engineering by producing <strong className="text-rose-400">Stellar Essence (🌟)</strong>. This requires building a massive industrial empire and harnessing the power of a star.</p>
            </HelpSection>

            <HelpSection title="⛏️ The Core Loop">
                <p><strong>1. Click:</strong> Start by clicking the <strong className="text-white">"Mine Ore"</strong> button to gather your first resource.</p>
                <p><strong>2. Automate:</strong> Spend Ore to buy <strong className="text-cyan-400">Upgrades</strong> like Auto-Miners. These buildings work for you, generating resources automatically, even while you're away!</p>
                <p><strong>3. Expand:</strong> As you produce more, you'll unlock more advanced buildings that create new types of resources, pushing you further toward the endgame.</p>
            </HelpSection>

            <HelpSection title="📦 Resources">
                <p><strong>Ore (⛏️):</strong> The basic building block, gathered manually or by miners.</p>
                <p><strong>Energy (⚡):</strong> Powers your advanced machinery. Produced by Solar Panels and other generators.</p>
                <p><strong>Parts (⚙️):</strong> Complex components created by Smelters. Used for high-tier buildings and research.</p>
                <p><strong>Research Points (🔬):</strong> Unlocks powerful permanent bonuses. Generated by Research Labs.</p>
                <p><strong>Dyson Fragments (🌌):</strong> The first tier of exotic matter, used for prestiging and advanced construction.</p>
                <p><strong>Stellar Essence (🌟):</strong> The final, most precious resource, representing true mastery of cosmic engineering.</p>
            </HelpSection>

            <HelpSection title="🔬 Research">
                <p>Once you build a <strong className="text-white">Research Lab</strong>, you'll unlock the Research tab. Spend Research Points here to gain powerful, permanent boosts to your production, efficiency, and clicking power.</p>
            </HelpSection>

            <HelpSection title="✨ The Endgame: Prestige">
                <p>When you feel your progress slowing, you can <strong className="text-purple-300">Prestige</strong>. This resets most of your progress (resources, buildings) but converts your Dyson Fragments into <strong className="text-purple-300">Prestige Points</strong>.</p>
                <p>Instead of a simple bonus, these points are a currency you spend in the <strong className="text-purple-300">Prestige Upgrade Tree</strong>. Invest in powerful, permanent upgrades to customize your playstyle and make each new run faster and more strategic!</p>
            </HelpSection>
        </div>

        <button
          onClick={onClose}
          className="mt-6 flex-shrink-0 bg-cyan-500 hover:bg-cyan-400 text-black font-bold py-3 px-8 rounded-lg text-xl transition-transform transform hover:scale-105 clip-corner-sm"
        >
          Got It!
        </button>
      </div>
    </div>
  );
};

export default HelpModal;