import { Upgrade, Resources, Research } from './types';

export const INITIAL_RESOURCES: Resources = {
  energy: 0,
  ore: 0,
  parts: 0,
  dyson_fragments: 0,
  research_points: 0,
};

export const DYSON_SPHERE_GOAL = 1_000_000;

// The initial configuration for all available upgrades in the game.
export const UPGRADES_CONFIG: Upgrade[] = [
  {
    id: 'auto_miner',
    name: 'Auto-Miner',
    description: 'Automatically mines raw ore from the ground.',
    baseCost: { ore: 10, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 10, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.08,
    production: { ore: 0.5 },
    consumption: {},
    owned: 0,
    level: 1,
    tags: ['miner'],
  },
  {
    id: 'solar_panel',
    name: 'Solar Panel',
    description: 'Generates a steady stream of energy from the sun.',
    unlocksAt: { owned: { auto_miner: 5 } },
    baseCost: { ore: 100, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 100, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.10,
    production: { energy: 5 },
    consumption: {},
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'industrial_drill',
    name: 'Industrial Drill',
    description: 'A heavy-duty drill that rapidly extracts ore, but requires energy.',
    unlocksAt: { owned: { solar_panel: 10 }, resources: { ore: 1000 } },
    baseCost: { ore: 250, energy: 50, parts: 0, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 250, energy: 50, parts: 0, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.12,
    production: { ore: 5 },
    consumption: { energy: 1 },
    owned: 0,
    level: 1,
    tags: ['miner'],
    synergies: [
        {
            sourceId: 'solar_panel',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: {
                type: 'flat',
                value: 1,
                per: 5,
            }
        }
    ]
  },
  {
    id: 'geothermal_plant',
    name: 'Geothermal Plant',
    description: 'Taps into the planet\'s core for a reliable, but maintenance-heavy, power source.',
    unlocksAt: { owned: { industrial_drill: 1 } },
    baseCost: { ore: 500, energy: 0, parts: 25, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 500, energy: 0, parts: 25, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.18,
    production: { energy: 20 },
    consumption: { parts: 0.1 },
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'smelter',
    name: 'Smelter',
    description: 'Refines ore into usable machinery parts.',
    unlocksAt: { owned: { industrial_drill: 5 } },
    baseCost: { ore: 500, energy: 100, parts: 0, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 500, energy: 100, parts: 0, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.25,
    production: { parts: 2 },
    consumption: { ore: 5, energy: 5 },
    owned: 0,
    level: 1,
    tags: ['factory'],
    synergies: [
        {
            sourceId: 'quarry_excavator',
            targetStat: 'production',
            targetResource: 'parts',
            bonus: {
                type: 'percentage_of_source_output',
                value: 0.05,
                sourceResource: 'ore',
            }
        }
    ]
  },
   {
    id: 'quarry_excavator',
    name: 'Quarry Excavator',
    description: 'A massive machine that carves out entire sections of rock.',
    unlocksAt: { owned: { smelter: 10 }, resources: { parts: 50 } },
    baseCost: { ore: 1000, energy: 200, parts: 50, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 1000, energy: 200, parts: 50, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.25,
    production: { ore: 25 },
    consumption: { energy: 10 },
    owned: 0,
    level: 1,
    tags: ['miner'],
  },
  {
    id: 'advanced_smelter',
    name: 'Advanced Smelter',
    description: 'Uses plasma injection to refine ore into parts with higher efficiency.',
    unlocksAt: { owned: { quarry_excavator: 5 }, resources: { parts: 500 } },
    baseCost: { ore: 2000, energy: 500, parts: 250, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 2000, energy: 500, parts: 250, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.22,
    production: { parts: 5 },
    consumption: { ore: 8, energy: 10 },
    owned: 0,
    level: 1,
    tags: ['factory'],
  },
  {
    id: 'part_combustor',
    name: 'Ore Plasma Torch',
    description: 'Consumes raw ore to generate a large amount of energy.',
    unlocksAt: { resources: { parts: 250 } },
    baseCost: { ore: 5000, energy: 1000, parts: 50, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 5000, energy: 1000, parts: 50, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.25,
    production: { energy: 50 },
    consumption: { ore: 15 },
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'research_lab',
    name: 'Research Lab',
    description: 'Generates Research Points to unlock powerful technologies.',
    unlocksAt: { owned: { smelter: 5 }, resources: { parts: 100 } },
    baseCost: { ore: 0, energy: 500, parts: 200, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 0, energy: 500, parts: 200, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.3,
    production: { research_points: 0.5 },
    consumption: { energy: 20, parts: 1 },
    owned: 0,
    level: 1,
    tags: ['factory'],
  },
  {
    id: 'fabricator',
    name: 'Part Fabricator',
    description: 'Assembles parts into fragments of a Dyson Sphere.',
    unlocksAt: { resources: { parts: 1000, energy: 2500 } },
    baseCost: { ore: 0, energy: 5000, parts: 1000, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 0, energy: 5000, parts: 1000, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.3,
    production: { dyson_fragments: 0.1 },
    consumption: { energy: 100, parts: 10 },
    owned: 0,
    level: 1,
  },
  {
    id: 'drone_bay',
    name: 'Drone Bay',
    description: 'Deploys automated mining drones that gain a production bonus from other miners.',
    unlocksAt: { owned: { quarry_excavator: 10 } },
    baseCost: { ore: 10000, energy: 2000, parts: 1000, dyson_fragments: 0, research_points: 0 },
    cost: { ore: 10000, energy: 2000, parts: 1000, dyson_fragments: 0, research_points: 0 },
    costMultiplier: 1.18,
    production: { ore: 50 },
    consumption: { energy: 25 },
    owned: 0,
    level: 1,
    tags: ['miner'],
    synergies: [
        {
            sourceId: 'auto_miner',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: { type: 'flat', value: 0.1, per: 1 }
        },
        {
            sourceId: 'industrial_drill',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: { type: 'flat', value: 0.5, per: 1 }
        }
    ]
  },
  {
    id: 'fusion_reactor',
    name: 'Fusion Reactor',
    description: 'A miniature star that consumes Dyson Fragments to generate immense power.',
    unlocksAt: { owned: { fabricator: 5 }, resources: { dyson_fragments: 10 } },
    baseCost: { energy: 10000, parts: 5000, dyson_fragments: 5, ore: 0, research_points: 0 },
    cost: { energy: 10000, parts: 5000, dyson_fragments: 5, ore: 0, research_points: 0 },
    costMultiplier: 1.35,
    production: { energy: 1000 },
    consumption: { dyson_fragments: 0.01 },
    owned: 0,
    level: 1,
    tags: ['power', 'exotic'],
  },
  {
    id: 'self_replicating_assembler',
    name: 'Self-Replicating Assembler',
    description: 'An autonomous factory that consumes parts to slowly build more of itself.',
    unlocksAt: { owned: { fusion_reactor: 1 } },
    baseCost: { parts: 10000, dyson_fragments: 20, energy: 0, ore: 0, research_points: 0 },
    cost: { parts: 10000, dyson_fragments: 20, energy: 0, ore: 0, research_points: 0 },
    costMultiplier: 1.5,
    production: {}, // No direct production
    consumption: { parts: 25 }, // Consumes parts to replicate
    owned: 0,
    level: 1,
    tags: ['factory', 'exotic'],
    specialEffect: 'self_replicating',
  },
];


// Configuration for all researchable technologies.
export const RESEARCH_CONFIG: Research[] = [
    // Click Path
    {
        id: 'reinforced_pickaxe',
        name: 'Reinforced Pickaxe',
        description: 'Strengthens your manual mining tool, doubling ore from clicks (+100%).',
        cost: { amount: 10, resource: 'research_points' },
        target: 'click',
        type: 'click_multiplier',
        value: 2,
    },
    {
        id: 'ergonomics',
        name: 'Ergonomic Tools',
        description: 'Improves manual dexterity, doubling click output again (+100%).',
        cost: { amount: 75, resource: 'research_points' },
        target: 'click',
        type: 'click_multiplier',
        value: 2,
        prerequisites: ['reinforced_pickaxe'],
    },
    // Miner Path
    {
        id: 'gears_1',
        name: 'Improved Gears',
        description: 'Boosts the output of all mining machines by 5%.',
        cost: { amount: 15, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.05,
    },
    {
        id: 'gears_2',
        name: 'Lubricated Gears',
        description: 'Boosts the output of all mining machines by another 5%.',
        cost: { amount: 50, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.05,
        prerequisites: ['gears_1'],
    },
    {
        id: 'gears_3',
        name: 'Hardened Gears',
        description: 'Boosts the output of all mining machines by another 10%.',
        cost: { amount: 100, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.1,
        prerequisites: ['gears_2'],
    },
    {
        id: 'gears_4',
        name: 'Titanium Gears',
        description: 'Boosts the output of all mining machines by a further 15%.',
        cost: { amount: 400, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.15,
        prerequisites: ['gears_3'],
    },
    {
        id: 'gears_5',
        name: 'Iridium Gears',
        description: 'Boosts the output of all mining machines by an additional 20%.',
        cost: { amount: 1000, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.20,
        prerequisites: ['gears_4'],
    },
    // Power Path
    {
        id: 'photovoltaics_1',
        name: 'Improved Photovoltaics',
        description: 'Boosts the output of all power generators by 5%.',
        cost: { amount: 30, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.05,
    },
    {
        id: 'photovoltaics_2',
        name: 'Concentrated Solar',
        description: 'Boosts the output of all power generators by another 10%.',
        cost: { amount: 120, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.1,
        prerequisites: ['photovoltaics_1'],
    },
     {
        id: 'photovoltaics_3',
        name: 'Quantum Solar Cells',
        description: 'Boosts the output of all power generators by 15%.',
        cost: { amount: 450, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.15,
        prerequisites: ['photovoltaics_2'],
    },
    // Factory Path
    {
        id: 'assembly_line_1',
        name: 'Basic Assembly Line',
        description: 'Boosts the output of all factory machines by 10%.',
        cost: { amount: 150, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.1,
    },
    {
        id: 'assembly_line_2',
        name: 'Automated Assembly',
        description: 'Boosts the output of all factory machines by another 15%.',
        cost: { amount: 500, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.15,
        prerequisites: ['assembly_line_1'],
    },
    {
        id: 'assembly_line_3',
        name: 'Robotic Assemblers',
        description: 'Boosts the output of all factory machines by a final 20%.',
        cost: { amount: 1200, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.20,
        prerequisites: ['assembly_line_2'],
    },
    // --- Efficiency Research ---
    {
        id: 'power_efficiency_1',
        name: 'Efficient Wiring',
        description: 'Reduces the energy consumption of all machines by 5%.',
        cost: { amount: 250, resource: 'research_points' },
        target: 'all',
        type: 'consumption_multiplier',
        value: 0.95,
    },
    {
        id: 'part_efficiency_1',
        name: 'Automated Logistics',
        description: 'Reduces the part consumption of all machines by 5%.',
        cost: { amount: 400, resource: 'research_points' },
        target: 'all',
        type: 'consumption_multiplier',
        value: 0.95,
        prerequisites: ['power_efficiency_1'],
    },
    // --- Exotic Research (Costs Dyson Fragments) ---
    {
        id: 'prestige_potency_1',
        name: 'Prestige Potency I',
        description: 'Each Prestige Point now grants an additional 0.1% production bonus.',
        cost: { amount: 1, resource: 'dyson_fragments' },
        target: 'prestige', // Custom target for special handling
        type: 'production_multiplier',
        value: 0.1,
        tags: ['exotic'],
    },
    {
        id: 'synergy_resonance_1',
        name: 'Synergy Resonance',
        description: 'Increases the effectiveness of all building synergies by 10%.',
        cost: { amount: 5, resource: 'dyson_fragments' },
        target: 'synergy', // Custom target for special handling
        type: 'synergy_multiplier',
        value: 1.1,
        tags: ['exotic'],
        prerequisites: ['prestige_potency_1'],
    },
    {
        id: 'auto_clicker_1',
        name: 'Automated Mining Drone',
        description: 'Automatically clicks the "Mine Ore" button once per second, gaining 10% of your manual click bonus.',
        cost: { amount: 10, resource: 'dyson_fragments' },
        target: 'click',
        type: 'auto_click',
        value: 0.1, // 10% of click bonus
        tags: ['exotic'],
        prerequisites: ['synergy_resonance_1'],
    },
];