import { Upgrade, Resources, Research, PrestigeUpgrade } from './types';

export const INITIAL_RESOURCES: Resources = {
  energy: 0,
  ore: 0,
  parts: 0,
  dyson_fragments: 0,
  research_points: 0,
  condensed_fragments: 0,
  stellar_essence: 0,
};

export const STELLAR_ESSENCE_GOAL = 1_000_000;

// The initial configuration for all available upgrades in the game.
export const UPGRADES_CONFIG: Upgrade[] = [
  // ... [Existing Tier 1-3 buildings] ...
  {
    id: 'auto_miner',
    name: 'Auto-Miner',
    description: 'Automatically mines raw ore from the ground.',
    baseCost: { ore: 10, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 10, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.08,
    production: { ore: 0.5 },
    consumption: {},
    owned: 0,
    level: 1,
    tags: ['miner'],
  },
  {
    id: 'solar_panel',
    name: 'Solar Panel',
    description: 'Generates a steady stream of energy from the sun.',
    unlocksAt: { owned: { auto_miner: 5 } },
    baseCost: { ore: 100, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 100, energy: 0, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.10,
    production: { energy: 5 },
    consumption: {},
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'industrial_drill',
    name: 'Industrial Drill',
    description: 'A heavy-duty drill that rapidly extracts ore, but requires energy.',
    unlocksAt: { owned: { solar_panel: 10 }, resources: { ore: 1000 } },
    baseCost: { ore: 250, energy: 50, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 250, energy: 50, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.12,
    production: { ore: 5 },
    consumption: { energy: 1 },
    owned: 0,
    level: 1,
    tags: ['miner'],
    synergies: [
        {
            sourceId: 'solar_panel',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: {
                type: 'flat',
                value: 1,
                per: 5,
            }
        }
    ]
  },
  {
    id: 'geothermal_plant',
    name: 'Geothermal Plant',
    description: 'Taps into the planet\'s core for a reliable, but maintenance-heavy, power source.',
    unlocksAt: { owned: { industrial_drill: 1 } },
    baseCost: { ore: 500, energy: 0, parts: 25, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 500, energy: 0, parts: 25, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.18,
    production: { energy: 20 },
    consumption: { parts: 0.1 },
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'smelter',
    name: 'Smelter',
    description: 'Refines ore into usable machinery parts.',
    unlocksAt: { owned: { industrial_drill: 5 } },
    baseCost: { ore: 500, energy: 100, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 500, energy: 100, parts: 0, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.25,
    production: { parts: 2 },
    consumption: { ore: 5, energy: 5 },
    owned: 0,
    level: 1,
    tags: ['factory'],
    synergies: [
        {
            sourceId: 'quarry_excavator',
            targetStat: 'production',
            targetResource: 'parts',
            bonus: {
                type: 'percentage_of_source_output',
                value: 0.05,
                sourceResource: 'ore',
            }
        }
    ]
  },
   {
    id: 'quarry_excavator',
    name: 'Quarry Excavator',
    description: 'A massive machine that carves out entire sections of rock.',
    unlocksAt: { owned: { smelter: 10 }, resources: { parts: 50 } },
    baseCost: { ore: 1000, energy: 200, parts: 50, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 1000, energy: 200, parts: 50, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.25,
    production: { ore: 25 },
    consumption: { energy: 10 },
    owned: 0,
    level: 1,
    tags: ['miner'],
  },
  {
    id: 'advanced_smelter',
    name: 'Advanced Smelter',
    description: 'Uses plasma injection to refine ore into parts with higher efficiency.',
    unlocksAt: { owned: { quarry_excavator: 5 }, resources: { parts: 500 } },
    baseCost: { ore: 2000, energy: 500, parts: 250, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 2000, energy: 500, parts: 250, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.22,
    production: { parts: 5 },
    consumption: { ore: 8, energy: 10 },
    owned: 0,
    level: 1,
    tags: ['factory'],
  },
  {
    id: 'ore_plasma_torch',
    name: 'Ore Plasma Torch',
    description: 'Consumes raw ore to generate a large amount of energy.',
    unlocksAt: { resources: { parts: 250 } },
    baseCost: { ore: 5000, energy: 1000, parts: 50, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 5000, energy: 1000, parts: 50, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.25,
    production: { energy: 50 },
    consumption: { ore: 15 },
    owned: 0,
    level: 1,
    tags: ['power'],
  },
  {
    id: 'research_lab',
    name: 'Research Lab',
    description: 'Generates Research Points to unlock powerful technologies.',
    unlocksAt: { owned: { smelter: 5 }, resources: { parts: 100 } },
    baseCost: { ore: 0, energy: 500, parts: 200, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 0, energy: 500, parts: 200, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.3,
    production: { research_points: 0.5 },
    consumption: { energy: 20, parts: 1 },
    owned: 0,
    level: 1,
    tags: ['factory'],
  },
  {
    id: 'fabricator',
    name: 'Part Fabricator',
    description: 'Assembles parts into fragments of a Dyson Sphere.',
    unlocksAt: { resources: { parts: 1000, energy: 2500 } },
    baseCost: { ore: 0, energy: 5000, parts: 1000, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 0, energy: 5000, parts: 1000, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.3,
    production: { dyson_fragments: 0.1 },
    consumption: { energy: 100, parts: 10 },
    owned: 0,
    level: 1,
    synergies: [
      {
        sourceId: 'fusion_reactor',
        targetStat: 'production',
        targetResource: 'dyson_fragments',
        bonus: {
          type: 'flat',
          value: 0.05, // +0.05 fragments/sec per Fusion Reactor
          per: 1,
        }
      }
    ]
  },
  {
    id: 'drone_bay',
    name: 'Drone Bay',
    description: 'Deploys automated mining drones that gain a production bonus from other miners.',
    unlocksAt: { owned: { quarry_excavator: 10 } },
    baseCost: { ore: 10000, energy: 2000, parts: 1000, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { ore: 10000, energy: 2000, parts: 1000, dyson_fragments: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.18,
    production: { ore: 50 },
    consumption: { energy: 25 },
    owned: 0,
    level: 1,
    tags: ['miner'],
    synergies: [
        {
            sourceId: 'auto_miner',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: { type: 'flat', value: 0.1, per: 1 }
        },
        {
            sourceId: 'industrial_drill',
            targetStat: 'production',
            targetResource: 'ore',
            bonus: { type: 'flat', value: 0.5, per: 1 }
        }
    ]
  },
  {
    id: 'fusion_reactor',
    name: 'Fusion Reactor',
    description: 'A miniature star that consumes Dyson Fragments to generate immense power.',
    unlocksAt: { owned: { fabricator: 5 }, resources: { dyson_fragments: 10 } },
    baseCost: { energy: 10000, parts: 5000, dyson_fragments: 5, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { energy: 10000, parts: 5000, dyson_fragments: 5, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.35,
    production: { energy: 1000 },
    consumption: { dyson_fragments: 0.01 },
    owned: 0,
    level: 1,
    tags: ['power', 'exotic'],
  },
  {
    id: 'quantum_forge',
    name: 'Quantum Forge',
    description: 'A highly advanced forge that converts raw energy and Dyson Fragments directly into complex machinery parts.',
    unlocksAt: { owned: { fusion_reactor: 1 } },
    baseCost: { parts: 25000, dyson_fragments: 50, energy: 15000, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { parts: 25000, dyson_fragments: 50, energy: 15000, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.4,
    production: { parts: 50 },
    consumption: { energy: 500, dyson_fragments: 0.1 },
    owned: 0,
    level: 1,
    tags: ['factory', 'exotic'],
  },
  {
    id: 'fragment_condenser',
    name: 'Fragment Condenser',
    description: 'Compresses Dyson Fragments into a denser, more exotic form of matter.',
    unlocksAt: { owned: { quantum_forge: 10 }, resources: { dyson_fragments: 1000 } },
    baseCost: { parts: 100000, dyson_fragments: 500, energy: 50000, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    cost: { parts: 100000, dyson_fragments: 500, energy: 50000, ore: 0, research_points: 0, condensed_fragments: 0, stellar_essence: 0 },
    costMultiplier: 1.25,
    production: { condensed_fragments: 0.5 },
    consumption: { energy: 2500, dyson_fragments: 1 },
    owned: 0,
    level: 1,
    tags: ['factory', 'exotic'],
  },
  {
    id: 'stellar_forge',
    name: 'Stellar Forge',
    description: 'The ultimate achievement in engineering. Forges Condensed Fragments into pure Stellar Essence.',
    unlocksAt: { owned: { fragment_condenser: 5 }, resources: { condensed_fragments: 100 } },
    baseCost: { parts: 1000000, dyson_fragments: 0, energy: 250000, ore: 0, research_points: 0, condensed_fragments: 100, stellar_essence: 0 },
    cost: { parts: 1000000, dyson_fragments: 0, energy: 250000, ore: 0, research_points: 0, condensed_fragments: 100, stellar_essence: 0 },
    costMultiplier: 1.3,
    production: { stellar_essence: 0.1 },
    consumption: { energy: 10000, condensed_fragments: 1 },
    owned: 0,
    level: 1,
    tags: ['factory', 'exotic'],
  },
];


// Configuration for all researchable technologies.
export const RESEARCH_CONFIG: Research[] = [
    // Click Path
    {
        id: 'reinforced_pickaxe',
        name: 'Reinforced Pickaxe',
        description: 'Strengthens your manual mining tool, doubling ore from clicks (+100%).',
        cost: { amount: 25, resource: 'research_points' },
        target: 'click',
        type: 'click_multiplier',
        value: 2,
    },
    {
        id: 'ergonomics',
        name: 'Ergonomic Tools',
        description: 'Improves manual dexterity, increasing click output by 150%.',
        cost: { amount: 150, resource: 'research_points' },
        target: 'click',
        type: 'click_multiplier',
        value: 2.5,
        prerequisites: ['reinforced_pickaxe'],
    },
    // Miner Path
    {
        id: 'gears_1',
        name: 'Improved Gears',
        description: 'Boosts the output of all mining machines by 10%.',
        cost: { amount: 50, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.10,
    },
    {
        id: 'gears_2',
        name: 'Lubricated Gears',
        description: 'Boosts the output of all mining machines by another 15%.',
        cost: { amount: 200, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.15,
        prerequisites: ['gears_1'],
    },
    {
        id: 'gears_3',
        name: 'Hardened Gears',
        description: 'Boosts the output of all mining machines by another 20%.',
        cost: { amount: 500, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.2,
        prerequisites: ['gears_2'],
    },
    {
        id: 'gears_4',
        name: 'Titanium Gears',
        description: 'Boosts the output of all mining machines by a further 25%.',
        cost: { amount: 1200, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.25,
        prerequisites: ['gears_3'],
    },
    {
        id: 'gears_5',
        name: 'Iridium Gears',
        description: 'Boosts the output of all mining machines by an additional 30%.',
        cost: { amount: 3000, resource: 'research_points' },
        target: 'miner',
        type: 'production_multiplier',
        value: 1.30,
        prerequisites: ['gears_4'],
    },
    // Power Path
    {
        id: 'photovoltaics_1',
        name: 'Improved Photovoltaics',
        description: 'Boosts the output of all power generators by 10%.',
        cost: { amount: 75, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.10,
    },
    {
        id: 'photovoltaics_2',
        name: 'Concentrated Solar',
        description: 'Boosts the output of all power generators by another 20%.',
        cost: { amount: 300, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.2,
        prerequisites: ['photovoltaics_1'],
    },
     {
        id: 'photovoltaics_3',
        name: 'Quantum Solar Cells',
        description: 'Boosts the output of all power generators by 25%.',
        cost: { amount: 900, resource: 'research_points' },
        target: 'power',
        type: 'production_multiplier',
        value: 1.25,
        prerequisites: ['photovoltaics_2'],
    },
    // Factory Path
    {
        id: 'assembly_line_1',
        name: 'Basic Assembly Line',
        description: 'Boosts the output of all factory machines by 15%.',
        cost: { amount: 250, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.15,
    },
    {
        id: 'assembly_line_2',
        name: 'Automated Assembly',
        description: 'Boosts the output of all factory machines by another 20%.',
        cost: { amount: 800, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.20,
        prerequisites: ['assembly_line_1'],
    },
    {
        id: 'assembly_line_3',
        name: 'Robotic Assemblers',
        description: 'Boosts the output of all factory machines by a final 25%.',
        cost: { amount: 2500, resource: 'research_points' },
        target: 'factory',
        type: 'production_multiplier',
        value: 1.25,
        prerequisites: ['assembly_line_2'],
    },
    // --- Efficiency Research ---
    {
        id: 'power_efficiency_1',
        name: 'Efficient Wiring',
        description: 'Reduces the energy consumption of all machines by 10%.',
        cost: { amount: 600, resource: 'research_points' },
        target: 'all',
        type: 'consumption_multiplier',
        value: 0.90,
    },
    {
        id: 'part_efficiency_1',
        name: 'Automated Logistics',
        description: 'Reduces the part consumption of all machines by 10%.',
        cost: { amount: 1000, resource: 'research_points' },
        target: 'all',
        type: 'consumption_multiplier',
        value: 0.90,
        prerequisites: ['power_efficiency_1'],
    },
    // --- Exotic Research (Costs Dyson Fragments) ---
    {
        id: 'prestige_potency_1',
        name: 'Prestige Potency I',
        description: 'Each Prestige Point now grants an additional 0.05% production bonus.',
        cost: { amount: 5, resource: 'dyson_fragments' },
        target: 'prestige',
        type: 'production_multiplier',
        value: 0.05,
        tags: ['exotic'],
    },
    {
        id: 'synergy_resonance_1',
        name: 'Synergy Resonance',
        description: 'Increases the effectiveness of all building synergies by 15%.',
        cost: { amount: 15, resource: 'dyson_fragments' },
        target: 'synergy',
        type: 'synergy_multiplier',
        value: 1.15,
        tags: ['exotic'],
        prerequisites: ['prestige_potency_1'],
    },
    {
        id: 'auto_clicker_1',
        name: 'Automated Mining Drone',
        description: 'Automatically clicks the "Mine Ore" button once per second, gaining 25% of your manual click bonus.',
        cost: { amount: 30, resource: 'dyson_fragments' },
        target: 'click',
        type: 'auto_click',
        value: 0.25,
        tags: ['exotic'],
        prerequisites: ['synergy_resonance_1'],
    },
    {
        id: 'prestige_potency_2',
        name: 'Prestige Potency II',
        description: 'Each Prestige Point now grants an additional 0.1% production bonus.',
        cost: { amount: 50, resource: 'dyson_fragments' },
        target: 'prestige',
        type: 'production_multiplier',
        value: 0.1,
        tags: ['exotic'],
        prerequisites: ['prestige_potency_1'],
    },
    {
        id: 'exotic_engineering',
        name: 'Exotic Engineering',
        description: 'Boosts the output of all Exotic buildings (e.g., Fusion Reactors) by 50%.',
        cost: { amount: 100, resource: 'dyson_fragments' },
        target: 'exotic',
        type: 'production_multiplier',
        value: 1.5,
        tags: ['exotic'],
        prerequisites: ['auto_clicker_1', 'prestige_potency_2'],
    },
    {
        id: 'quantum_logistics',
        name: 'Quantum Logistics',
        description: 'Reduces the resource consumption of all machines by a further 15%.',
        cost: { amount: 200, resource: 'dyson_fragments' },
        target: 'all',
        type: 'consumption_multiplier',
        value: 0.85,
        tags: ['exotic'],
        prerequisites: ['exotic_engineering'],
    },
    {
        id: 'prestige_potency_3',
        name: 'Prestige Potency III',
        description: 'Each Prestige Point grants an additional 0.15% production bonus, for a staggering total.',
        cost: { amount: 500, resource: 'dyson_fragments' },
        target: 'prestige',
        type: 'production_multiplier',
        value: 0.15,
        tags: ['exotic'],
        prerequisites: ['quantum_logistics'],
    },
    {
        id: 'singularity_harnessing',
        name: 'Singularity Harnessing',
        description: 'Your understanding of spacetime allows all buildings to produce 25% more output.',
        cost: { amount: 1000, resource: 'dyson_fragments' },
        target: 'all',
        type: 'production_multiplier',
        value: 1.25,
        tags: ['exotic'],
        prerequisites: ['prestige_potency_3'],
    },
];

export const PRESTIGE_UPGRADES_CONFIG: PrestigeUpgrade[] = [
    {
        id: 'global_production_boost',
        name: 'Global Production Boost',
        description: (level, value) => `Increases all resource production by ${((value - 1) * 100).toFixed(0)}%.`,
        maxLevel: 20,
        cost: level => 1 + Math.floor(Math.pow(level, 1.5)),
        type: 'production_multiplier',
        target: 'all',
        value: level => 1 + level * 0.05, // +5% per level
    },
    {
        id: 'click_power_boost',
        name: 'Click Power',
        description: (level, value) => `Increases manual click power by ${((value - 1) * 100).toFixed(0)}%.`,
        maxLevel: 10,
        cost: level => 2 * (level + 1),
        type: 'click_multiplier',
        target: 'click',
        value: level => 1 + level * 0.25, // +25% per level
    },
    {
        id: 'building_cost_reduction',
        name: 'Engineering Efficiency',
        description: (level, value) => `Reduces the cost of all buildings by ${(100 - value * 100).toFixed(1)}%.`,
        maxLevel: 10,
        cost: level => 5 + Math.floor(Math.pow(level, 2)),
        type: 'cost_reduction',
        target: 'all_buildings',
        value: level => 1 - level * 0.025, // -2.5% per level
    },
    {
        id: 'starting_ore',
        name: 'Geological Survey',
        description: (level, value) => `Start each prestige with ${value.toLocaleString()} extra ore.`,
        maxLevel: 5,
        cost: level => 1 * (level + 1),
        type: 'production_multiplier', // Note: This is a special case handled in prestige logic
        target: 'starting_ore',
        value: level => level * 100, // +100 ore per level
    },
    {
        id: 'miner_production_boost',
        name: 'Mining Guild Charter',
        description: (level, value) => `Increases production of all 'miner' type buildings by ${((value - 1) * 100).toFixed(0)}%.`,
        maxLevel: 15,
        cost: level => 2 + level,
        type: 'production_multiplier',
        target: 'miner',
        value: level => 1 + level * 0.1, // +10% per level
    },
    {
        id: 'power_production_boost',
        name: 'Energy Grid Optimization',
        description: (level, value) => `Increases production of all 'power' type buildings by ${((value - 1) * 100).toFixed(0)}%.`,
        maxLevel: 15,
        cost: level => 2 + level,
        type: 'production_multiplier',
        target: 'power',
        value: level => 1 + level * 0.1, // +10% per level
    },
    {
        id: 'factory_production_boost',
        name: 'Factory Overclock',
        description: (level, value) => `Increases production of all 'factory' type buildings by ${((value - 1) * 100).toFixed(0)}%.`,
        maxLevel: 15,
        cost: level => 2 + level,
        type: 'production_multiplier',
        target: 'factory',
        value: level => 1 + level * 0.1, // +10% per level
    },
];